# Neural Networks

<img src='./image/neural_net.jpeg'>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(42)

In [2]:
class Neural_Networks(object):
    def __init__(self):
        pass
    
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    def sigmoid_prime(self, x):
        return self.sigmoid(x) * (1 - self.sigmoid(x))
    def error_formula(self, y, output):
        return - y*np.log(output) - (1 - y) * np.log(1-output)
    
    def error_term_formula(self, x, y, output):
        return (y - output) * self.sigmoid_prime(x)
    
    def train_test_splite(self, features, targets, ratio):
        if features.shape[0] != targets.shape[0]:
            print("ERROR! Train and Test data unequal.")
        else:
            test_size = int(len(features) * ratio)
            train_X = features[test_size:]
            train_y = targets[test_size:]
            test_X  = features[:test_size]
            test_y  = targets[:test_size]
        return train_X, train_y, test_X, test_y
    
    def evaluate(self, weights, test_features, test_targets):
        test_out = self.sigmoid(np.dot(test_features, weights))
        predictions = test_out > 0.5
        accuracy = np.mean(predictions == test_targets)
        print("Prediction accuracy: {:.3f}".format(accuracy))
    
    def train(self, features, targets, epochs, learnrate):
        n_records, n_features = features.shape
        last_loss = None

        weights = np.random.normal(scale=1 / n_features**.5, size=n_features)

        for e in range(epochs):
            del_w = np.zeros(weights.shape)
            for x, y in zip(features, targets):
                output = self.sigmoid(np.dot(x, weights))
                error = self.error_formula(y, output)
                error_term = self.error_term_formula(x, y, output)
                del_w += error_term * x

            weights += learnrate * del_w / n_records

            if e % (epochs / 10) == 0:
                out = self.sigmoid(np.dot(features, weights))
                loss = np.mean((out - targets) ** 2)
                #print("Epoch:", e)
                if last_loss and last_loss < loss:
                    print("Train loss: ", loss, "  WARNING - Loss Increasing")
                else:
                    print("Epoch:", e ,"Train loss: ", loss)
                last_loss = loss
        print("Training Finished!")
        return weights

## Data Scaling

In [3]:
churn_df = pd.read_csv("../Datasets/CHURNDATA/ChurnData.csv")
churn_df.head()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,4.40,...,1.0,0.0,1.0,1.0,0.0,1.482,3.033,4.913,4.0,1.0
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,9.45,...,0.0,0.0,0.0,0.0,0.0,2.246,3.240,3.497,1.0,1.0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,6.30,...,0.0,0.0,0.0,1.0,0.0,1.841,3.240,3.401,3.0,0.0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,6.05,...,1.0,1.0,1.0,1.0,1.0,1.800,3.807,4.331,4.0,0.0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,7.10,...,0.0,0.0,1.0,1.0,0.0,1.960,3.091,4.382,3.0,0.0

In [13]:
churn_df = churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','churn']]
churn_df['churn'] = churn_df['churn'].astype('int')
churn_df.head(20)

,tenure,age,address,income,ed,employ,equip,callcard,wireless,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,1
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,1
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,0
5,68.0,52.0,17.0,120.0,1.0,24.0,0.0,1.0,0.0,0
6,42.0,40.0,7.0,37.0,2.0,8.0,1.0,1.0,1.0,0
7,9.0,21.0,1.0,17.0,2.0,2.0,0.0,0.0,0.0,0
8,35.0,50.0,26.0,140.0,2.0,21.0,0.0,1.0,0.0,0
9,49.0,51.0,27.0,63.0,4.0,19.0,0.0,1.0,0.0,0
10,56.0,52.0,28.0,49.0,2.0,12.0,0.0,1.0,0.0,0
11,47.0,40.0,16.0,127.0,4.0,12.0,1.0,1.0,0.0,0
12,56.0,50.0,1.0,80.0,2.0,24.0,0.0,1.0,1.0,0
13,69.0,51.0,11.0,438.0,4.0,23.0,1.0,1.0,0.0,0
14,16.0,27.0,5.0,37.0,3.0,5.0,0.0,0.0,0.0,0
15,4.0,35.0,16.0,161.0,5.0,6.0,1.0,0.0,1.0,1
16,27.0,51.0,3.0,80.0,5.0,11.0,1.0,0.0,0.0,0
17,52.0,61.0,3.0,53.0,5.0,1.0,1.0,1.0,1.0,0
18,64.0,25.0,4.0,76.0,3.0,2.0,1.0,1.0,0.0,0
19,12.0,24.0,2.0,19.0,1.0,0.0,0.0,1.0,0.0,1

In [5]:
features = np.asarray(churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])

In [6]:
features[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.]])

In [7]:
targets = np.asarray(churn_df['churn'])

In [8]:
targets[0:5]

array([1, 1, 0, 0, 0])

In [9]:
nn = Neural_Networks()

In [10]:
train_X, train_y, test_X, test_y = nn.train_test_splite(features, targets, 0.2)

In [11]:
weights = nn.train(train_X, train_y, epochs = 200, learnrate = 0.5)

c:\python36\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in log
  # Remove the CWD from sys.path while we load stuff.
c:\python36\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in multiply
  # Remove the CWD from sys.path while we load stuff.

Epoch: 0 Train loss:  0.6874857120324699
Epoch: 20 Train loss:  0.6772205218277662
Epoch: 40 Train loss:  0.6494214452355699
Epoch: 60 Train loss:  0.5991262310139014
Epoch: 80 Train loss:  0.5737411888980886
Epoch: 100 Train loss:  0.5394413947564157
Epoch: 120 Train loss:  0.5092196962831282
Epoch: 140 Train loss:  0.500528027643292
Epoch: 160 Train loss:  0.4996119634289366
Train loss:  0.5023552425287281   WARNING - Loss Increasing
Training Finished!

In [12]:
nn.evaluate(weights, test_X, test_y)

Prediction accuracy: 0.475